name: Hexo Auto Deploy CI

on:
  push:
    branches: [source]
  pull_request:
    branches: [source]

env:
  GIT_USER: iaosee
  GIT_EMAIL: iaosee@outlook.com
  THEME_REPO: izhaoo/hexo-theme-zhaoo
  THEME_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Checkout blog repo
        uses: actions/checkout@v2
        with:
          ref: source

      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: themes/zhaoo

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_KEY_PRI: ${{secrets.HEXO_DEPLOY_KEY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_KEY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          cp _config.theme.zhaoo.yml themes/zhaoo/_config.yml

      - name: Install dependencies
        run: |
          npm i

      - name: Deploy blog
        run: |
          npm run clean
          npm run deploy
